package twcore.bots.pokerbot;

public enum PokerTableGameState {
    WAITING_FOR_PLAYERS,
    STARTING_GAME,
    ROTATE_ACTOR_SMALL_BLIND,
    POST_SMALL_BLIND,
    ROTATE_ACTOR_BIG_BLIND,
    POST_BIG_BLIND,
    DO_TABLE_ACTION,
    DEAL_HOLE_CARDS,
    DEAL_COMMUNITY_CARDS,
    ROTATE_ACTOR,
    WAIT_PLAYER_ACTION,
    CHECK_PLAYER_ACTION,
    START_BETTING_ROUND,
    END_BETTING_ROUND,
    SHOWDOWN,
    GAME_OVER,
    PAUSE_PERIOD,
}